server:
  port: 8082
#spring:
#  datasource:
#    username: user
#    password: password
#    url: jdbc:mysql://db:3306/MarketplaceDB
#    driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/MarketplaceDB
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
kafka:
  server: kafka:29092
  offset-reset: latest
  topics:
    regist: notification.event
  groupid:
    regist: group.notification.event